apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zt0bym51z-go 
  janus-idp.io/tekton: zt0bym51z-go
  backstage.io/kubernetes-id: zt0bym51z-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zt0bym51z-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  